apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./voting-app/k8s-specifications/db-deployment.yaml
- ./voting-app/k8s-specifications/db-persistentvolumeclaim.yaml
- ./voting-app/k8s-specifications/db-service.yaml
- ./voting-app/k8s-specifications/redis-deployment.yaml
- ./voting-app/k8s-specifications/redis-persistentvolumeclaim.yaml
- ./voting-app/k8s-specifications/redis-service.yaml
- ./voting-app/k8s-specifications/result-deployment.yaml
- ./voting-app/k8s-specifications/result-service.yaml
- ./voting-app/k8s-specifications/vote-deployment.yaml
- ./voting-app/k8s-specifications/vote-service.yaml
- ./voting-app/k8s-specifications/worker-deployment.yaml
- ./voting-app/k8s-specifications/result-ingress.yaml
- ./voting-app/k8s-specifications/vote-ingress.yaml
