apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: vote
    context: voting-app/vote/
    kaniko: {}
  - image: worker
    context: voting-app/worker/
  - image: result
    context: voting-app/result/
manifests:
  kustomize:
    paths:
    - .
