apiVersion: skaffold/v4beta2
kind: Config
build:
  cluster:
    concurrency: 0
    # pullSecretName: kaniko-secret
    randomDockerConfigSecret: false
    randomPullSecret: false
  artifacts:
  - image: vote
    context: voting-app/vote/
  - image: worker
    context: voting-app/worker/
  - image: result
    context: voting-app/result/

manifests:
  kustomize:
    paths:
    - .
