name: Skaffold Test Workflow

on:
    pull_request:
      types: [opened,reopened,synchronize,closed]

permissions:
    contents: read
    pull-requests: write
    id-token: write

jobs:
    # Try
    try:
        name: Skaffold Docker build
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Create/Connect to Uffizzi Virtual Cluster
            - name: Connect to Virtual Cluster
              uses: UffizziCloud/cluster-action@main
              with:
                cluster-name: pr-${{ github.event.pull_request.number }}

            - name: Build Docker images
              uses: hiberbee/github-action-skaffold@1.20.0
              with:
                command: dev
                repository: registry.uffizzi.com